server:
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces


logging:
  file:
    name: D:/spring-logs/${spring.application.name}.log
#  pattern:
#    level: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name}] [%t] [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"