spring:
  cloud:
    gateway:
      routes:
        - id: monitor-service
          uri: lb://monitor-service
          predicates:
            - Path=/monitor/**
        - id: email-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notify/**
